// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI;

namespace WebAPI.Migrations
{
    [DbContext(typeof(OtdelKadrovDbContext))]
    partial class OtdelKadrovDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebAPI.Models.Education", b =>
                {
                    b.Property<int>("Education_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Education_ID");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("WebAPI.Models.Otdel", b =>
                {
                    b.Property<int>("Otdel_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.HasKey("Otdel_ID");

                    b.ToTable("Otdels");
                });

            modelBuilder.Entity("WebAPI.Models.Position", b =>
                {
                    b.Property<int>("Position_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Oklad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionName_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Position_ID");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("WebAPI.Models.Sotrud", b =>
                {
                    b.Property<int>("Sotrud_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Education_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Education_ID1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("F_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("L_Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Otdel_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Otdel_ID1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Position_ID1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Sotrud_ID");

                    b.HasIndex("Education_ID1");

                    b.HasIndex("Otdel_ID1");

                    b.HasIndex("Position_ID1");

                    b.ToTable("Sotruds");
                });

            modelBuilder.Entity("WebAPI.Models.Sotrud", b =>
                {
                    b.HasOne("WebAPI.Models.Education", "Education")
                        .WithMany("Sotruds")
                        .HasForeignKey("Education_ID1");

                    b.HasOne("WebAPI.Models.Otdel", "Otdel")
                        .WithMany("Sotruds")
                        .HasForeignKey("Otdel_ID1");

                    b.HasOne("WebAPI.Models.Position", "Position")
                        .WithMany("Sotruds")
                        .HasForeignKey("Position_ID1");

                    b.Navigation("Education");

                    b.Navigation("Otdel");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("WebAPI.Models.Education", b =>
                {
                    b.Navigation("Sotruds");
                });

            modelBuilder.Entity("WebAPI.Models.Otdel", b =>
                {
                    b.Navigation("Sotruds");
                });

            modelBuilder.Entity("WebAPI.Models.Position", b =>
                {
                    b.Navigation("Sotruds");
                });
#pragma warning restore 612, 618
        }
    }
}
