CREATE TABLE Otdel(
Otdel_ID INTEGER NOT NULL PRIMARY KEY,
Name VARCHAR(30) NOT NULL,
Telephone VARCHAR(20) NOT NULL
);

CREATE TABLE Position(
Position_ID INTEGER NOT NULL  PRIMARY KEY,
PositionName_ID INTEGER NOT NULL,
Oklad INTEGER NOT NULL,
Status INTEGER NOT NULL
);

CREATE TABLE Education(
Education_ID INTEGER NOT NULL PRIMARY KEY,
Name VARCHAR(30) NOT NULL
);

CREATE TABLE Sotrud(
Sotrud_ID INTEGER NOT NULL PRIMARY KEY,
Otdel_ID INTEGER 
		REFERENCES Otdel(Otdel_ID),
Position_ID INTEGER 
		REFERENCES Position(Position_ID),
Education_ID INTEGER 
		REFERENCES Education(Education_ID),
F_Name VARCHAR(30) NOT NULL,
L_Name VARCHAR(30) NOT NULL
);



