// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2;

namespace WebApplication2.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20221010214300_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebApplication2.Models.Education", b =>
                {
                    b.Property<int>("Education_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Education_ID");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("WebApplication2.Models.Otdel", b =>
                {
                    b.Property<int>("Otdel_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Otdel_ID");

                    b.ToTable("Otdels");
                });

            modelBuilder.Entity("WebApplication2.Models.Position", b =>
                {
                    b.Property<int>("Position_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Oklad")
                        .HasColumnType("int");

                    b.Property<int>("PositionName_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Position_ID");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("WebApplication2.Models.Sotrud", b =>
                {
                    b.Property<int>("Sotrud_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Education_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Education_ID1")
                        .HasColumnType("int");

                    b.Property<string>("F_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("L_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Otdel_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Otdel_ID1")
                        .HasColumnType("int");

                    b.Property<int>("Position_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Position_ID1")
                        .HasColumnType("int");

                    b.HasKey("Sotrud_ID");

                    b.HasIndex("Education_ID1");

                    b.HasIndex("Otdel_ID1");

                    b.HasIndex("Position_ID1");

                    b.ToTable("Sotruds");
                });

            modelBuilder.Entity("WebApplication2.Models.Sotrud", b =>
                {
                    b.HasOne("WebApplication2.Models.Education", "Education")
                        .WithMany()
                        .HasForeignKey("Education_ID1");

                    b.HasOne("WebApplication2.Models.Otdel", "Otdel")
                        .WithMany("Sotruds")
                        .HasForeignKey("Otdel_ID1");

                    b.HasOne("WebApplication2.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("Position_ID1");

                    b.Navigation("Education");

                    b.Navigation("Otdel");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("WebApplication2.Models.Otdel", b =>
                {
                    b.Navigation("Sotruds");
                });
#pragma warning restore 612, 618
        }
    }
}
